# Generated by Django 5.1.3 on 2024-11-19 17:04

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Input the Student's First Name", max_length=100, verbose_name="Student's First Name")),
                ('middle_name', models.CharField(help_text="Input the Student's Second Name", max_length=100, verbose_name="Student's Second Name")),
                ('last_name', models.CharField(help_text="Input the Student's Surname Name", max_length=100, verbose_name="Student's Surname Name")),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('clas_of_admission', models.CharField(choices=[('PLAYGROUP', 'Playgroup'), ('PRENURSERY', 'Prenursery'), ('NURSERY1', 'Nursery1'), ('NURSERY2', 'Nursery 2'), ('PRIMARY1', 'Primary 1'), ('PRIMARY2', 'Primary 2'), ('PRIMARY3', 'Primary 3'), ('PRIMARY4', 'Primary 4'), ('PRIMARY5', 'Primary 5'), ('PRIMARY6', 'Primary 6'), ('SUMMER', 'Summer')], max_length=15, verbose_name='Class Of Admission')),
                ('parent_name', models.CharField(help_text='Enter the name of parent', max_length=200, verbose_name="Parent's Name")),
                ('parent_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=14, region='NG', verbose_name="Parent's Phone Number")),
                ('parent_email', models.EmailField(help_text='Provide Valide Email Address', max_length=254, verbose_name='Email Address')),
                ('address', models.CharField(max_length=200, verbose_name='Residential Address')),
                ('date_created', models.DateField(auto_now=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('enquiry_reason', models.TextField(max_length=1600)),
                ('sent_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_event', models.DateField()),
                ('time_of_event', models.TimeField()),
                ('title_of_event', models.CharField(max_length=150)),
                ('event_content', models.CharField(max_length=200)),
                ('event_photo', models.ImageField(blank=True, null=True, upload_to='eventsimages/')),
            ],
        ),
        migrations.CreateModel(
            name='Eventpicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picker', models.CharField(blank=True, max_length=6, null=True)),
                ('picker_eid', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
